name = "blog-api"
main = "src/index.ts"
compatibility_date = "2024-02-20"

[vars]
FRONTEND_URL = "http://localhost:3000"

[[d1_databases]]
binding = "DB"
database_name = "blog_db"
database_id = ""

[[kv_namespaces]]
binding = "CACHE"
id = "" 