name = "blog-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-01-01"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "${CLOUDFLARE_D1_DATABASE_ID}"  # 使用环境变量

# KV 命名空间配置
[[kv_namespaces]]
binding = "BLOG_CACHE"
id = "${CLOUDFLARE_KV_NAMESPACE_ID}"  # 使用环境变量

[site]
bucket = "./.next"

[build]
command = "npm run build"
watch_dir = "app"

[routes]
pattern = "/api/*"
zone_name = "blog-ai-mine.pages.dev" 