name = "blog-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-01-01"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = ""  # 将从环境变量获取

# KV 命名空间配置
[[kv_namespaces]]
binding = "BLOG_CACHE"
id = ""  # 将从环境变量获取

[site]
bucket = "./.next"  # Next.js 输出目录 