name = "blog-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = ""

[[kv_namespaces]]
binding = "BLOG_CACHE"
id = "" 